# Generated by Django 4.0.5 on 2022-06-29 08:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Educations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('univer', models.CharField(max_length=50, verbose_name='Навчальний заклад')),
                ('spec', models.CharField(max_length=50, verbose_name='Спеціальність')),
                ('degree', models.CharField(choices=[('so', 'Середньо-освітний'), ('st', 'Середньо-технічний'), ('nhl', 'Неповна вища освіта'), ('hl', 'Вища освіта'), ('m', 'Магістр'), ('kds', 'Кандидат у доктора наук'), ('ds', 'Доктор наук'), (None, 'Оберіть ступінь')], default='st', max_length=3, verbose_name='Ступінь освіти')),
                ('about', models.TextField(verbose_name='Головне')),
                ('date_start', models.DateField(verbose_name='З')),
                ('date_over', models.DateField(verbose_name='По')),
            ],
            options={
                'verbose_name': 'Освіта',
                'verbose_name_plural': 'Освіти',
                'ordering': ['-date_over'],
            },
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=25, verbose_name='Захоплення')),
            ],
            options={
                'verbose_name': 'Захоплення',
                'verbose_name_plural': 'Захоплення',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ua', 'Українська'), ('en', 'Англійська'), ('ru', 'Російська'), (None, 'Оберіть мову')], max_length=2, verbose_name='Мова')),
                ('level', models.CharField(choices=[('l', 'Низький'), ('m', 'Середній'), ('h', 'Високий'), ('n', 'Рідна мова'), (None, 'Оберіть рівень')], max_length=1, verbose_name='Рівень')),
            ],
            options={
                'verbose_name': 'Мова',
                'verbose_name_plural': 'Мови',
            },
        ),
        migrations.CreateModel(
            name='Locations_Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=25, verbose_name='Країна')),
            ],
            options={
                'verbose_name': 'Країна',
                'verbose_name_plural': 'Країни',
            },
        ),
        migrations.CreateModel(
            name='Locations_Sity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sity', models.CharField(max_length=25, verbose_name='Місто')),
            ],
            options={
                'verbose_name': 'Місто',
                'verbose_name_plural': 'Міста',
            },
        ),
        migrations.CreateModel(
            name='WhyMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Персональна якість')),
                ('about', models.TextField(verbose_name='Докладніше')),
            ],
            options={
                'verbose_name': 'Якості',
                'verbose_name_plural': 'Якості',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='WorkHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.CharField(choices=[('f', 'Повна занятість'), ('h', 'Часткова занятість'), ('o', 'Віддалена праця')], default='f', max_length=1)),
            ],
            options={
                'verbose_name': 'Ступінь зайнятості',
                'verbose_name_plural': 'Ступені зайнятості',
            },
        ),
        migrations.CreateModel(
            name='WorkPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.CharField(max_length=50, verbose_name='Компанія')),
                ('prof', models.CharField(max_length=50, verbose_name='Спеціальність')),
                ('about', models.TextField(verbose_name='Головне')),
                ('date_start', models.DateField(verbose_name='З')),
                ('date_over', models.DateField(verbose_name='По')),
            ],
            options={
                'verbose_name': 'Місце роботи',
                'verbose_name_plural': 'Місця роботи',
                'ordering': ['-date_over'],
            },
        ),
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Використано недопустимі символи', regex='^[А-Яа-яёЁЇїІіЄєҐґ\\s]+$')], verbose_name='ПІБ')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('position', models.CharField(max_length=50, verbose_name='Вакансія')),
                ('about', models.TextField(validators=[django.core.validators.RegexValidator(message='Використано недопустимі символи', regex='^[А-Яа-яёЁЇїІіЄєҐґ\\s]+$')], verbose_name='Про себе')),
                ('age', models.IntegerField(verbose_name='Вік')),
                ('birthday', models.DateField(verbose_name='Дата народження')),
                ('phone', models.CharField(max_length=18, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Пошта')),
                ('photo', models.ImageField(upload_to='workers_foto/', verbose_name='Фото')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Дата публікації')),
                ('educations', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='site_app.educations', verbose_name='Освіта')),
                ('interests', models.ManyToManyField(related_query_name='info', to='site_app.interests', verbose_name='Захоплення')),
                ('languages', models.ManyToManyField(related_query_name='info', to='site_app.languages', verbose_name='Мова')),
                ('location_country', models.ManyToManyField(related_query_name='info', to='site_app.locations_country', verbose_name='Країна')),
                ('location_sity', models.ManyToManyField(related_query_name='info', to='site_app.locations_sity', verbose_name='Місто')),
                ('work_hour', models.ManyToManyField(related_query_name='info', to='site_app.workhours', verbose_name='Ступінь зайнятості')),
                ('workplaces', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='site_app.workplaces', verbose_name='Попередні місця роботи')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
                'ordering': ['-published'],
            },
        ),
    ]
