# Generated by Django 4.0.6 on 2022-07-25 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Educations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('univer', models.CharField(max_length=100, verbose_name='Навчальний заклад')),
                ('univer_uk', models.CharField(max_length=100, null=True, verbose_name='Навчальний заклад')),
                ('univer_en', models.CharField(max_length=100, null=True, verbose_name='Навчальний заклад')),
                ('spec', models.CharField(max_length=50, verbose_name='Спеціальність')),
                ('spec_uk', models.CharField(max_length=50, null=True, verbose_name='Спеціальність')),
                ('spec_en', models.CharField(max_length=50, null=True, verbose_name='Спеціальність')),
                ('degree', models.CharField(choices=[('so', 'Середньо-освітний'), ('st', 'Середньо-технічний'), ('nhl', 'Неповна вища освіта'), ('hl', 'Вища освіта'), ('univer', "Master's degree"), ('m', 'Магістр'), ('kds', 'Кандидат у доктора наук'), ('ds', 'Доктор наук'), (None, 'Оберіть ступінь')], max_length=6, verbose_name='Ступінь освіти')),
                ('degree_uk', models.CharField(choices=[('so', 'Середньо-освітний'), ('st', 'Середньо-технічний'), ('nhl', 'Неповна вища освіта'), ('hl', 'Вища освіта'), ('univer', "Master's degree"), ('m', 'Магістр'), ('kds', 'Кандидат у доктора наук'), ('ds', 'Доктор наук'), (None, 'Оберіть ступінь')], max_length=6, null=True, verbose_name='Ступінь освіти')),
                ('degree_en', models.CharField(choices=[('so', 'Середньо-освітний'), ('st', 'Середньо-технічний'), ('nhl', 'Неповна вища освіта'), ('hl', 'Вища освіта'), ('univer', "Master's degree"), ('m', 'Магістр'), ('kds', 'Кандидат у доктора наук'), ('ds', 'Доктор наук'), (None, 'Оберіть ступінь')], max_length=6, null=True, verbose_name='Ступінь освіти')),
                ('about', models.TextField(verbose_name='Головне')),
                ('about_uk', models.TextField(null=True, verbose_name='Головне')),
                ('about_en', models.TextField(null=True, verbose_name='Головне')),
                ('date_start', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], verbose_name='З')),
                ('date_start_uk', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], null=True, verbose_name='З')),
                ('date_start_en', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], null=True, verbose_name='З')),
                ('date_over', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], verbose_name='По')),
                ('date_over_uk', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], null=True, verbose_name='По')),
                ('date_over_en', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], null=True, verbose_name='По')),
            ],
            options={
                'verbose_name': 'Освіта',
                'verbose_name_plural': 'Освіти',
                'ordering': ['-date_over'],
            },
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=25, verbose_name='Захоплення')),
                ('interest_uk', models.CharField(max_length=25, null=True, verbose_name='Захоплення')),
                ('interest_en', models.CharField(max_length=25, null=True, verbose_name='Захоплення')),
            ],
            options={
                'verbose_name': 'Захоплення',
                'verbose_name_plural': 'Захоплення',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ua', 'Українська'), ('en', 'Англійська'), ('ru', 'Російська'), ('ua-en', 'Ukranian'), ('en-en', 'English'), (None, 'Оберіть мову')], max_length=5, verbose_name='Мова')),
                ('language_uk', models.CharField(choices=[('ua', 'Українська'), ('en', 'Англійська'), ('ru', 'Російська'), ('ua-en', 'Ukranian'), ('en-en', 'English'), (None, 'Оберіть мову')], max_length=5, null=True, verbose_name='Мова')),
                ('language_en', models.CharField(choices=[('ua', 'Українська'), ('en', 'Англійська'), ('ru', 'Російська'), ('ua-en', 'Ukranian'), ('en-en', 'English'), (None, 'Оберіть мову')], max_length=5, null=True, verbose_name='Мова')),
                ('level', models.CharField(choices=[('low', 'Низький'), ('medium', 'Середній'), ('high', 'Високий'), ('native', 'Рідна мова'), ('A', 'Beginner'), ('B', 'Average'), ('C', 'Advanced'), ('I', 'Fluent'), (None, 'Оберіть рівень')], max_length=6, verbose_name='Рівень')),
                ('level_uk', models.CharField(choices=[('low', 'Низький'), ('medium', 'Середній'), ('high', 'Високий'), ('native', 'Рідна мова'), ('A', 'Beginner'), ('B', 'Average'), ('C', 'Advanced'), ('I', 'Fluent'), (None, 'Оберіть рівень')], max_length=6, null=True, verbose_name='Рівень')),
                ('level_en', models.CharField(choices=[('low', 'Низький'), ('medium', 'Середній'), ('high', 'Високий'), ('native', 'Рідна мова'), ('A', 'Beginner'), ('B', 'Average'), ('C', 'Advanced'), ('I', 'Fluent'), (None, 'Оберіть рівень')], max_length=6, null=True, verbose_name='Рівень')),
            ],
            options={
                'verbose_name': 'Мова',
                'verbose_name_plural': 'Мови',
            },
        ),
        migrations.CreateModel(
            name='Locations_Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=25, verbose_name='Країна')),
                ('country_uk', models.CharField(max_length=25, null=True, verbose_name='Країна')),
                ('country_en', models.CharField(max_length=25, null=True, verbose_name='Країна')),
            ],
            options={
                'verbose_name': 'Країна',
                'verbose_name_plural': 'Країни',
            },
        ),
        migrations.CreateModel(
            name='Locations_Sity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sity', models.CharField(max_length=25, verbose_name='Місто')),
                ('sity_uk', models.CharField(max_length=25, null=True, verbose_name='Місто')),
                ('sity_en', models.CharField(max_length=25, null=True, verbose_name='Місто')),
            ],
            options={
                'verbose_name': 'Місто',
                'verbose_name_plural': 'Міста',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва проекту')),
                ('name_uk', models.CharField(max_length=50, null=True, verbose_name='Назва проекту')),
                ('name_en', models.CharField(max_length=50, null=True, verbose_name='Назва проекту')),
                ('teh', models.CharField(max_length=50, verbose_name='Технологія')),
                ('teh_uk', models.CharField(max_length=50, null=True, verbose_name='Технологія')),
                ('teh_en', models.CharField(max_length=50, null=True, verbose_name='Технологія')),
                ('url', models.CharField(max_length=50, verbose_name='GitHub посилання')),
                ('pic', models.ImageField(upload_to='portfolio/', verbose_name='Картинка портфоліо')),
            ],
            options={
                'verbose_name': 'Портфоліо',
                'verbose_name_plural': 'Портфоліо',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SkillHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=50, verbose_name='Етап розвитку')),
                ('stage_uk', models.CharField(max_length=50, null=True, verbose_name='Етап розвитку')),
                ('stage_en', models.CharField(max_length=50, null=True, verbose_name='Етап розвитку')),
                ('about', models.TextField(verbose_name='Головне')),
                ('about_uk', models.TextField(null=True, verbose_name='Головне')),
                ('about_en', models.TextField(null=True, verbose_name='Головне')),
                ('date_start', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], verbose_name='З')),
                ('date_over', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], verbose_name='По')),
            ],
            options={
                'verbose_name': 'Стадія розвитку вміння',
                'verbose_name_plural': 'Стадії розвитку вмінь',
                'ordering': ['-date_over', 'stage'],
            },
        ),
        migrations.CreateModel(
            name='WhyMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Персональна якість')),
                ('type_uk', models.CharField(max_length=50, null=True, verbose_name='Персональна якість')),
                ('type_en', models.CharField(max_length=50, null=True, verbose_name='Персональна якість')),
                ('about', models.TextField(verbose_name='Докладніше')),
                ('about_uk', models.TextField(null=True, verbose_name='Докладніше')),
                ('about_en', models.TextField(null=True, verbose_name='Докладніше')),
                ('pic', models.ImageField(null=True, upload_to='why_me/', verbose_name='Картинка якості')),
            ],
            options={
                'verbose_name': 'Якості',
                'verbose_name_plural': 'Якості',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='WorkHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.CharField(choices=[('f', 'Повна занятість'), ('h', 'Часткова занятість'), ('o', 'Віддалена праця'), ('a', 'All day'), ('p', 'Part-time employment'), ('r', 'Remote working'), (None, 'Оберіть ступінь')], default='f', max_length=1)),
                ('hours_uk', models.CharField(choices=[('f', 'Повна занятість'), ('h', 'Часткова занятість'), ('o', 'Віддалена праця'), ('a', 'All day'), ('p', 'Part-time employment'), ('r', 'Remote working'), (None, 'Оберіть ступінь')], default='f', max_length=1, null=True)),
                ('hours_en', models.CharField(choices=[('f', 'Повна занятість'), ('h', 'Часткова занятість'), ('o', 'Віддалена праця'), ('a', 'All day'), ('p', 'Part-time employment'), ('r', 'Remote working'), (None, 'Оберіть ступінь')], default='f', max_length=1, null=True)),
            ],
            options={
                'verbose_name': 'Ступінь зайнятості',
                'verbose_name_plural': 'Ступені зайнятості',
            },
        ),
        migrations.CreateModel(
            name='WorkPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.CharField(max_length=50, verbose_name='Компанія')),
                ('firma_uk', models.CharField(max_length=50, null=True, verbose_name='Компанія')),
                ('firma_en', models.CharField(max_length=50, null=True, verbose_name='Компанія')),
                ('prof', models.CharField(max_length=50, verbose_name='Спеціальність')),
                ('prof_uk', models.CharField(max_length=50, null=True, verbose_name='Спеціальність')),
                ('prof_en', models.CharField(max_length=50, null=True, verbose_name='Спеціальність')),
                ('about', models.TextField(verbose_name='Головне')),
                ('about_uk', models.TextField(null=True, verbose_name='Головне')),
                ('about_en', models.TextField(null=True, verbose_name='Головне')),
                ('date_start', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], verbose_name='З')),
                ('date_start_uk', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], null=True, verbose_name='З')),
                ('date_start_en', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], null=True, verbose_name='З')),
                ('date_over', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], verbose_name='По')),
                ('date_over_uk', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], null=True, verbose_name='По')),
                ('date_over_en', models.IntegerField(choices=[(1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], null=True, verbose_name='По')),
            ],
            options={
                'verbose_name': 'Місце роботи',
                'verbose_name_plural': 'Місця роботи',
                'ordering': ['-date_over'],
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50, verbose_name='Вміння')),
                ('skill_uk', models.CharField(max_length=50, null=True, verbose_name='Вміння')),
                ('skill_en', models.CharField(max_length=50, null=True, verbose_name='Вміння')),
                ('shortly', models.TextField(verbose_name='Стисло')),
                ('shortly_uk', models.TextField(null=True, verbose_name='Стисло')),
                ('shortly_en', models.TextField(null=True, verbose_name='Стисло')),
                ('logo', models.ImageField(null=True, upload_to='logo/', verbose_name='Значок')),
                ('stages', models.ManyToManyField(related_query_name='stages', to='site_app.skillhistory', verbose_name='Етап розвитку')),
            ],
            options={
                'verbose_name': 'Вміння',
                'verbose_name_plural': 'Вміння',
                'ordering': ['skill'],
            },
        ),
        migrations.CreateModel(
            name='MainInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=50, verbose_name='ПІБ')),
                ('fio_uk', models.CharField(max_length=50, null=True, verbose_name='ПІБ')),
                ('fio_en', models.CharField(max_length=50, null=True, verbose_name='ПІБ')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('position', models.CharField(max_length=50, verbose_name='Вакансія')),
                ('position_uk', models.CharField(max_length=50, null=True, verbose_name='Вакансія')),
                ('position_en', models.CharField(max_length=50, null=True, verbose_name='Вакансія')),
                ('about', models.TextField(verbose_name='Про себе')),
                ('about_uk', models.TextField(null=True, verbose_name='Про себе')),
                ('about_en', models.TextField(null=True, verbose_name='Про себе')),
                ('age', models.IntegerField(verbose_name='Вік')),
                ('birthday', models.DateField(verbose_name='Дата народження')),
                ('birthday_uk', models.DateField(null=True, verbose_name='Дата народження')),
                ('birthday_en', models.DateField(null=True, verbose_name='Дата народження')),
                ('phone', models.CharField(max_length=18, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Пошта')),
                ('photo', models.ImageField(upload_to='workers_foto/', verbose_name='Фото')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Дата публікації')),
                ('educations', models.ManyToManyField(related_query_name='info', to='site_app.educations', verbose_name='Освіта')),
                ('interests', models.ManyToManyField(related_query_name='info', to='site_app.interests', verbose_name='Захоплення')),
                ('languages', models.ManyToManyField(related_query_name='info', to='site_app.languages', verbose_name='Мова')),
                ('location_country', models.ManyToManyField(related_query_name='info', to='site_app.locations_country', verbose_name='Країна')),
                ('location_sity', models.ManyToManyField(related_query_name='info', to='site_app.locations_sity', verbose_name='Місто')),
                ('skills', models.ManyToManyField(related_query_name='info', to='site_app.skills', verbose_name='Вміння')),
                ('whyme', models.ManyToManyField(related_query_name='info', to='site_app.whyme', verbose_name='Чому я')),
                ('work_hour', models.ManyToManyField(related_query_name='info', to='site_app.workhours', verbose_name='Ступінь зайнятості')),
                ('workplaces', models.ManyToManyField(related_query_name='info', to='site_app.workplaces', verbose_name='Попередні місця роботи')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
                'ordering': ['-published'],
            },
        ),
    ]
