# Generated by Django 4.0.5 on 2022-06-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maininfo',
            name='about',
            field=models.TextField(verbose_name='Про себе'),
        ),
        migrations.RemoveField(
            model_name='maininfo',
            name='educations',
        ),
        migrations.AddField(
            model_name='maininfo',
            name='educations',
            field=models.ManyToManyField(to='site_app.educations', verbose_name='Освіта'),
        ),
        migrations.RemoveField(
            model_name='maininfo',
            name='workplaces',
        ),
        migrations.AddField(
            model_name='maininfo',
            name='workplaces',
            field=models.ManyToManyField(to='site_app.workplaces', verbose_name='Попередні місця роботи'),
        ),
    ]
