# Generated by Django 4.0.5 on 2022-06-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0002_alter_maininfo_about_remove_maininfo_educations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maininfo',
            name='whyme',
            field=models.ManyToManyField(related_query_name='info', to='site_app.whyme', verbose_name='Чому я'),
        ),
        migrations.AlterField(
            model_name='educations',
            name='univer',
            field=models.CharField(max_length=100, verbose_name='Навчальний заклад'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='educations',
            field=models.ManyToManyField(related_query_name='info', to='site_app.educations', verbose_name='Освіта'),
        ),
        migrations.AlterField(
            model_name='maininfo',
            name='workplaces',
            field=models.ManyToManyField(related_query_name='info', to='site_app.workplaces', verbose_name='Попередні місця роботи'),
        ),
        migrations.AlterField(
            model_name='workhours',
            name='hours',
            field=models.CharField(choices=[('f', 'Повна занятість'), ('h', 'Часткова занятість'), ('o', 'Віддалена праця'), (None, 'Оберіть ступінь')], default='f', max_length=1),
        ),
    ]
