# Generated by Django 4.0.5 on 2022-07-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0003_maininfo_whyme_alter_educations_univer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50, verbose_name='Вміння')),
                ('shortly', models.TextField(verbose_name='Стисло')),
                ('about', models.TextField(verbose_name='Стисло')),
            ],
            options={
                'verbose_name': 'Вміння',
                'verbose_name_plural': 'Вміння',
                'ordering': ['skill'],
            },
        ),
        migrations.AddField(
            model_name='maininfo',
            name='skills',
            field=models.ManyToManyField(related_query_name='info', to='site_app.skills', verbose_name='Вміння'),
        ),
    ]
