# Generated by Django 4.0.5 on 2022-07-01 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0004_skills_maininfo_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='about',
        ),
        migrations.AddField(
            model_name='skills',
            name='logo',
            field=models.ImageField(null=True, upload_to='logo/', verbose_name='Значок'),
        ),
        migrations.CreateModel(
            name='SkillHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stages', models.CharField(max_length=50, verbose_name='Етап розвитку')),
                ('about', models.TextField(verbose_name='Головне')),
                ('date_start', models.DateField(verbose_name='З')),
                ('date_over', models.DateField(verbose_name='По')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='site_app.skills', verbose_name='Вміння')),
            ],
            options={
                'verbose_name': 'Історія розвитку',
                'verbose_name_plural': 'Історії розвитку',
                'ordering': ['-date_over'],
            },
        ),
        migrations.AddField(
            model_name='skills',
            name='stage',
            field=models.ManyToManyField(related_query_name='stage', to='site_app.skillhistory', verbose_name='Етап розвитку'),
        ),
    ]
