# Generated by Django 4.0.5 on 2022-07-01 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0005_remove_skills_about_skills_logo_skillhistory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillhistory',
            name='skill',
        ),
    ]
