# Generated by Django 4.0.5 on 2022-07-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0006_remove_skillhistory_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillhistory',
            old_name='stages',
            new_name='stage',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='stage',
        ),
        migrations.AddField(
            model_name='skills',
            name='stages',
            field=models.ManyToManyField(related_query_name='stages', to='site_app.skillhistory', verbose_name='Етап розвитку'),
        ),
    ]
