# Generated by Django 4.0.5 on 2022-07-04 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0009_alter_skillhistory_date_over_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillhistory',
            options={'ordering': ['-date_over', 'stage'], 'verbose_name': 'Стадія розвитку вміння', 'verbose_name_plural': 'Стадії розвитку вмінь'},
        ),
    ]
