# Generated by Django 4.0.5 on 2022-07-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0010_alter_skillhistory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва проекту')),
                ('teh', models.CharField(max_length=50, verbose_name='Технологія')),
                ('url', models.CharField(max_length=50, verbose_name='GitHub посилання')),
                ('pic', models.ImageField(upload_to='portfolio/', verbose_name='Картинка портфоліо')),
            ],
            options={
                'verbose_name': 'Портфоліо',
                'verbose_name_plural': 'Портфоліо',
                'ordering': ['name', 'teh'],
            },
        ),
    ]
